image_root: 'nlvr2'
ann_root: 'BLIP_nlvr/annotation'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_nlvr.pth'
#size of vit model; base or large
vit: 'base'
batch_size_train: 10
batch_size_test: 10
vit_grad_ckpt: False
vit_ckpt_layer: 0
max_epoch: 10

image_size: 384

# optimizer
weight_decay: 0.05
init_lr: 3e-5
min_lr: 0

